/*
Program Name: EECS 348 Assignment 2
Author: Lillian Bailey
Brief Description: Program prioritizes emails from a company CEO using a max heap. Emails are prioritized first by sender then by date.
If two emails have the same sender priority, the newer email is read first.
Inputs: File of commands (EMAIL, NEXT, READ, COUNT)
Outputs: NEXT displays the highest-priority email, COUNT displays the number of unread emails.
Collaborators: Original code generated by Gemini AI as per assignment 2 directiv, but modified by Lillian Bailey also as per directive.
Creation Date: 17SEP2026
Code Source Note: The original version of this code was generated by Gemini AI, but I added modifications for string handling, memory
allocation checks, organization, and command processing.  I marked this here so I could avoid a bunch of "This code was made by X"
comments
*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define INITIAL_CAPACITY 10
#define MAX_LINE 512

//Structure to represent one email
typedef struct {
    char sender [30];
    char subject[256];
    char date[11];
    int rank;
    int date_val;
} Email;

//Structure to represent a maxheap
typedef struct {
    Email *data;
    int size;
    int capacity;
} MaxHeap;

//Return the priority rank for a sender category. A larger rank means the email should be read first
int getRank(const char *category) {
    if (strcmp(category, "Boss") == 0) return 5;
    if (strcmp(category, "Subordinate") == 0) return 4;
    if (strcmp(category, "Peer") == 0) return 3;
    if (strcmp(category, "ImportantPerson") == 0) return 2;
    if (strcmp(category, "OtherPerson") == 0) return 1;
    return 0;
}

//Convert MM-DD-YYYY into YYYYMMDD. This allows dates to be compared numerically
int getDateVal(const char *dateStr) {
    int m, d, y;
    if (sscanf(dateStr, "%d-%d-%d", &m, &d, &y) == 3) {
        return y * 10000 + m * 100 + d;
    }
    return 0;
}

//Safely copy a string into a fixed-size destination array. Always leave room for the null terminator
void copyString(char *destination, size_t destinationSize, const char *source) {
    if (destinationSize == 0) {
        return;
    }
    strncpy(destination, source, destinationSize - 1);
    destination[destinationSize - 1] = '\0';
}

//Create and initialize an empty maxheap
MaxHeap *createHeap(void) {
    MaxHeap *h = malloc(sizeof(MaxHeap));

    //Check whether memory for the heap structure was allocated
    if (h == NULL) {
        fprintf(stderr, "Memory allocation failed.\n");
        exit(EXIT_FAILURE);
    }
    h->capacity = INITIAL_CAPACITY;
    h->size = 0;

    //Allocate the initial array of emails
    h->data = malloc(h->capacity * sizeof(Email));

    //Check whether memory for the email array was allocated
    if (h->data == NULL) {
        fprintf(stderr, "Memory allocation failed.\n");
        free(h);
        exit(EXIT_FAILURE);
    }
    return h;
}

//Free all memory used by the heap
void freeHeap(MaxHeap *h) {
    if (h == NULL) {
        return;
    }
    free(h->data);
    free(h);
}

//Swap two emails in the heap
void swap(Email *a, Email *b) {
    Email temp = *a;
    *a = *b;
    *b = temp;
}

//Compare two emails. Return a positive value if a has higher priority than b. Return a negative value if a has lower priority than b. Return 0 if they have equal priority and date
int compareEmails(const Email *a, const Email *b) {
    //Sender category is checked first. If they match, check the dates insatead
    if (a->rank != b->rank) {
        return a->rank - b->rank;
    }
    return a->date_val - b->date_val;
}

//Move an email upward until the maxheap property is restored
void heapifyUp(MaxHeap *h, int index) {
    while (index > 0) {
        //Calculate the parent index
        int parent = (index - 1)/2;

        //If the child has higher priority, swap with parent
        if (compareEmails(&h->data[index], &h->data[parent]) > 0) {
            swap(&h->data[index], &h->data[parent]);
            index = parent;
        } else {
            //Stop when the parent already has higher priority
            break;
        }
    }
}

//Move an email downward until the maxheap property is restored
void heapifyDown(MaxHeap *h, int index) {
    while (2 * index + 1 < h->size) {
        //Calculate the left and right child indices
        int left = 2 * index + 1;
        int right = 2 * index + 2;
        int largest = index;

        //Check whether the left child or right child has higher priority
        if (compareEmails(&h->data[left], &h->data[largest]) > 0) {
            largest = left;
        }
        if (right < h->size && compareEmails(&h->data[right], &h->data[largest]) > 0) {
            largest = right;
        }

        //If the current email is already highest, stop
        if (largest == index) {
            break;
        }

        //Swap with the higher-priority child
        swap(&h->data[index], &h->data[largest]);
        index = largest;
    }
}

// Insert a new email into the MaxHeap.
void insertEmail(MaxHeap *h, const char *sender, const char *subject, const char *date) {

    // If the array is full, double its capacity
    if (h->size >= h->capacity) {
        int newCapacity = h->capacity * 2;

        // Use a temporary pointer so realloc failure does not lose the original allocated array
        Email *newData = realloc(h->data, newCapacity * sizeof(Email));

        // Check whether the array was successfully resized
        if (newData == NULL) {
            fprintf(stderr, "Memory allocation failed.\n");
            freeHeap(h);
            exit(EXIT_FAILURE);
        }

        // Store the resized array and update its capacity
        h->data = newData;
        h->capacity = newCapacity;
    }

    // Create a new email and copy its information safely
    Email newEmail;

    copyString(newEmail.sender, sizeof(newEmail.sender), sender);

    copyString(newEmail.subject, sizeof(newEmail.subject), subject);

    copyString(newEmail.date, sizeof(newEmail.date), date);

    // Calculate the priority information for the email
    newEmail.rank = getRank(sender);
    newEmail.date_val = getDateVal(date);

    // Place the email at the end of the heap
    h->data[h->size] = newEmail;

    // Increase the number of emails before restoring heap order
    h->size++;

    // Move the new email upward if necessary
    heapifyUp(h, h->size - 1);
}

// Return a pointer to the highest-priority email. Return NULL if the heap is empty.
Email *peekMax(MaxHeap *h) {
    if (h->size <= 0) {
        return NULL;
    }

    return &h->data[0];
}

// Remove the highest-priority email from the heap
void extractMax(MaxHeap *h) {
    // Do nothing if there are no emails
    if (h->size <= 0) {
        return;
    }

    // Move the last email into the root position
    h->data[0] = h->data[h->size - 1];

    // Decrease the number of emails
    h->size--;

    // Restore the MaxHeap property if emails remain
    if (h->size > 0) {
        heapifyDown(h, 0);
    }
}

// Remove trailing newline and carriage return characters
void trimString(char *str) {
    size_t len = strlen(str);

    while (len > 0 && (str[len - 1] == '\n' || str[len - 1] == '\r')) {
        str[len - 1] = '\0';
        len--;
    }
}

// Process an EMAIL command. Format: EMAIL Sender,Subject,Date
void processEmail(MaxHeap *heap, char *line) {
    // Skip the "EMAIL " portion of the command
    char *rest = line + 6;

    // Find the first comma separating the sender and subject
    char *comma1 = strchr(rest, ',');

    if (comma1 == NULL) {
        return;
    }

    // Separate the sender from the rest of the command
    *comma1 = '\0';

    char *sender = rest;
    char *subjectAndDate = comma1 + 1;

    // Find the last comma separating the subject and date. This allows the subject to contain spaces.
    char *comma2 = strrchr(subjectAndDate, ',');

    if (comma2 == NULL) {
        return;
    }

    // Separate the subject from the date
    *comma2 = '\0';

    char *subject = subjectAndDate;
    char *date = comma2 + 1;

    // Insert the email into the MaxHeap
    insertEmail(heap, sender, subject, date);
}

// Process a NEXT command. Display the highest-priority unread email without removing it.
void processNext(MaxHeap *heap) {
    Email *top = peekMax(heap);

    // If there are no emails, do nothing
    if (top == NULL) {
        return;
    }

    // Display the email in the required format
    printf("Next email:\n");
    printf("Sender: %s\n", top->sender);
    printf("Subject: %s\n", top->subject);
    printf("Date: %s\n", top->date);
}

// Process a READ command. Remove the highest-priority unread email
void processRead(MaxHeap *heap) {
    extractMax(heap);
}

// Process a COUNT command. Display the number of unread emails
void processCount(MaxHeap *heap) {
    printf("There are %d emails to read.\n", heap->size);
}

// Main function: read and process commands from standard input
int main(void) {
    // Create the MaxHeap
    MaxHeap *heap = createHeap();

    // Store each input line in this character array
    char line[MAX_LINE];

    // Read commands until the end of the input file
    while (fgets(line, sizeof(line), stdin) != NULL) {
        // Remove the newline from the input
        trimString(line);

        // Ignore empty lines
        if (strlen(line) == 0) {
            continue;
        }

        // Determine which command was entered
        if (strncmp(line, "EMAIL ", 6) == 0) {
            processEmail(heap, line);
        }
        else if (strcmp(line, "COUNT") == 0) {
            processCount(heap);
        }
        else if (strcmp(line, "NEXT") == 0) {
            processNext(heap);
        }
        else if (strcmp(line, "READ") == 0) {
            processRead(heap);
        }
    }

    // Free the heap before ending the program
    freeHeap(heap);

    return 0;
}
